name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Expo CLI
        run: yarn global add eas-cli

      - name: Login to Expo
        run: expo login -u ${{ secrets.EXPO_CLI_USERNAME }} -p ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: Install project dependencies
        run: npm install

      - name: Build Android APK
        run: npx eas build --platform android

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-build
          path: <path/to/your/apk/*.apk>
